### PR TITLE
rob10470/include_collate_data

### PR DESCRIPTION
**Pull request by robert-craig-houston**
Issue: https://devtopia.esri.com/runtime/arcade/issues/940

The data file is created to only include the necessary files. Manually added .cpp files to .lua as needed for compilation of the following script: 
``` C++
   UErrorCode status = UErrorCode::U_ZERO_ERROR;
    const auto locale = icu::Locale::createFromName("en-US-u-va-posix");
    
   auto collator = icu::Collator::createInstance(locale, status);
   CPPUNIT_ASSERT_MESSAGE("Create collate should work", U_SUCCESS(status));
   const auto result = collator->compareUTF8("This is some text", "This is some other text",status);
   CPPUNIT_ASSERT_MESSAGE("Compare should work", U_SUCCESS(status));
   CPPUNIT_ASSERT_MESSAGE("Comparison result strange", result == UCollationResult::UCOL_GREATER);
``` 

Data file requires en_US_POSIX rather than the more modern en-US-u-va-posix.
We use the root unicode collation data that is less complex, `"collationUCAData": "implicithan",`

Will check size once certain it works on all platforms!

### CODE REVIEW

**Comment by robert-craig-houston** [comment]
General Vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/1528/

**Comment by robert-craig-houston** [comment]
General: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/1548/
UWP Debug + Friends: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/1549/

Might need to rerun, some innocuous vtest runs failing with unexpected segfaults.

**Comment by robert-craig-houston** [comment]
Tests above seem to have passed

Currently filling out a rough table of size changes: 
ThirdPartyBuilds:
Third party full build:  https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/105/
Third party empty build: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/106/

RTC Release builds:
Todo...

**Comment by robert-craig-houston** [comment]
In that case will be a second, kicking off some release builds so I have data on runtimecore build sizes, wouldn't want to mislead anyone with windows size changes!
 https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/1600/

Will be comparing sizes to the last good builds for each platform.

**Comment by robert-craig-houston** [comment]
Final results seem more in line with what I expected, it looks like a roughly 2% increase over last good dev, which size increase averaging around 2mb if we count IOS as an outlier

| Release/Test builds | new ICU kb | old ICU kb | Total Change kb | %Change     | New Runtime kb  | Old Runtime KB | Total change kb | % change    |
|---------------------|------------|------------|-----------------|-------------|-----------------|----------------|-----------------|-------------|
| Android x86         | 5102       | 3540       | 1562            | 44.12429379 |                 |                |                 |             |
| Android x64         | 5144       | 3568       | 1576            | 44.17040359 |                 |                |                 |             |
| Android Armv7       | 5294       | 3668       | 1626            | 44.32933479 |                 |                |                 |             |
| Android Arm64       | 5059       | 3513       | 1546            | 44.0079704  | 64485           | 62996.48       | 1488.52         | 2.362862179 |
|                     |            |            |                 |             |                 |                |                 |             |
| IOS Simx64          | 5361       | 3745       | 1616            | 43.15086782 |                 |                |                 |             |
| IOS SimArm64        | 5443       | 3800       | 1643            | 43.23684211 |                 |                |                 |             |
| IOS Catx64          | 5428       | 3791       | 1637            | 43.18121868 |                 |                |                 |             |
| IOS CatArm64        | 5476       | 3823       | 1653            | 43.23829453 |                 |                |                 |             |
| IOS Arm64           | 5269       | 3642       | 1627            | 44.67325645 | 339871          | 332062.72      | 7808.28         | 2.351447341 |
|                     |            |            |                 |             |                 |                |                 |             |
| Linux x64           | 5274       | 3693       | 1581            | 42.81072299 | 109798          | 107560.96      | 2237.04         | 2.079788057 |
|                     |            |            |                 |             |                 |                |                 |             |
| Mac x64             | 5445       | 3804       | 1641            | 43.13880126 | 127003          | 124303.36      | 2699.64         | 2.17181579  |
| Mac Arm64           | 5481       | 3828       | 1653            | 43.18181818 |                 |                |                 |             |
|                     |            |            |                 |             |                 |                |                 |             |
| Windows x64         | 71109      | 43548      | 27561           | 63.28878479 | 89870           | 87644.16       | 2225.84         | 2.539632989 |
| Windows x86         | 72116      | 44162      | 27954           | 63.29876364 |                 |                |                 |             |
|                     |            |            |                 |             |                 |                |                 |             |
| WinUWP x86          | 71858      | 43913      | 27945           | 63.63719172 |                 |                |                 |             |
| WinUWP x64          | 70832      | 43283      | 27549           | 63.64854562 |                 |                |                 |             |
| WinUWP arm64        | 70958      | 43393      | 27565           | 63.5240707  | 97772           | 95539.2        | 2232.8          | 2.337051179 |

**Comment by chri7325** [comment]
@robert-craig-houston that is quite a big jump that we won't be able to ever shave off with any optimizations or bloat.

**Comment by robert-craig-houston** [comment]
Gotcha, will aim for hitting tommorow before daily, and update runtime post daily.

**Pull request merged**
