### PR TITLE
arch: Add missing source files for sanitize

### PR DESCRIPTION
**Pull request by Craig-Proctor**
Add missing source files to allow sanitize builds

Updated from Slack:

>I built locally everything with the all_santize.lua,  create_build.sh -d all_santizeI was building geomodel_tests and it had linker errors. To resolve them I had to add the additional files. Nothing special

### CODE REVIEW

**Review by robert-craig-houston — APPROVED** [review]
Lgtm!

**Comment by robert-craig-houston** [comment]
3rd party Vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/185/

**Comment by robert-craig-houston** [comment]
Looks good so far, need to do a full sanitize build tommorow to confirm. Assuming we're kosher will merge this sometime this weekend then target Monday pre-noon build for updating RTC.

**Comment by Craig-Proctor** [comment]
Sounds great. Thank you

**Comment by robert-craig-houston** [comment]
Got some failures to build due to another 3rd party library updating.

 Going to rebuild + rerun before I put my foot in my mouth.

**Pull request merged**
